expenses/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('stm/', views.ajax_view_expense, name = 'ajax-view-expense'),
    path('upload-bank-statement/', views.upload_bank_statement, name = 'bank-statement-upload'),
    path('check-where-our-money-went/', views.expense_view, name = 'expense-content'),
    path('upload-reading/', views.upload_reading, name = 'reading-upload'),
    re_path(r'^expense-show/(?P<cats>[-\w]+)/(?P<dfrom>[-\w]+)/(?P<dto>[-\w]+)/$', views.expense_edit, name='expense-edit'),
    path('bank-statement/<int:pk>', views.ing_statement_detail_view.as_view(), name='bank-statement-content'),
]

warmehuisje/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('warmehuisje/', include('expenses.urls')),
    path('', RedirectView.as_view(url='warmehuisje/', permanent=True)),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

expenses/models.py
from django.db import models
from django.urls import reverse
from datetime import datetime as dt

from .storage import OverwriteStorage
import pandas as pd
# Create your models here.

col_rn = {'Datum': 'date', 'Naam / Omschrijving': 'name', 
          'Af Bij': 'af_bij', 'Bedrag (EUR)': 'amount'
         }
ing_cols = ['date', 'name', 'amount', 'category', 'description'] #, 'af_bij'



class expense_category(models.Model):
    name = models.TextField(max_length = 1000, help_text = 'expense category')
    frequency = models.IntegerField(unique = True, blank = True, null = True)
    
    class Meta:
        ordering = ['frequency']
        verbose_name = "Expense Category"
        verbose_name_plural = "Expense Categories"
    
    def __str__(self):
        return self.name
    
class expense(models.Model):
    date = models.DateField()
    name = models.TextField(max_length = 200)
    amount = models.FloatField(default = 0)
    category = models.ForeignKey('expense_category', on_delete = models.RESTRICT, 
                                 null = True, blank = True, related_name='category')
    description = models.TextField(max_length = 1000, help_text = 'enter a description', blank = True, null = True)  
    
    class Meta:
        ordering = ['-date', 'category', 'name']

    def __str__(self):
        return self.name
    

def statement_fn(instance, filename):
    if instance.cleansed:
        folder = 'cleansed'
    else:
        folder = 'raw'
    return '/'.join(['bank_statements', folder, filename])

def fix_saving(x):
    if ('Van Oranje' in x.Mededelingen):
        x.af_bij = 'Af'
        x.amount = -x.amount
    return x


class ing_statement(models.Model):
    cleansed = models.BooleanField(default = False)
    generated_on = models.DateTimeField(auto_now_add=True)
    csv_file = models.FileField(upload_to = statement_fn, storage=OverwriteStorage(),
                                help_text = "ING bank statements", blank = True, null = True)
    
    class Meta:
        ordering = ['-generated_on']
        verbose_name = "ING statement"
        verbose_name_plural = "ING statements"
    
    def filename(self):
        return self.csv_file.name.split('/')[-1]
        
    def date_from(self):
        try:
            date_part = self.csv_file.name.replace('.csv', '').split('_')[-2]
            return dt.strptime(date_part, '%d-%m-%Y').date()
        except:
            return None
    
    def date_to(self):
        try:
            date_part = self.csv_file.name.replace('.csv', '').split('_')[-1]
            return dt.strptime(date_part, '%d-%m-%Y').date()
        except:
            return None
    
    def load_raw(self):
        if 'raw' in self.csv_file.name:
            raw_data = pd.read_csv(self.csv_file, sep=';').astype({'Bedrag (EUR)': 'string', 'Tag': 'string'})
            preprep_data = raw_data\
              .assign(
                Datum = pd.to_datetime(raw_data.Datum.astype('str')).dt.date,
                category = None, #raw_data.Tag.str.split(r'#| #| ', expand = True)[1],
                description = None #raw_data.Tag.str.split(r'#| #| ', expand = True)[2],
            ).rename(columns = col_rn)
            
            altered_saving = preprep_data.assign(
                amount = preprep_data.amount.str.replace(',','.')
            ).astype({'amount': 'float'}).apply(fix_saving, axis = 1)
            
            loaded_data = altered_saving.loc[altered_saving.af_bij == "Af"]\
             .groupby(['date', 'name', 'category', 'description'], dropna=False)\
             .aggregate({'amount':'sum'}).round(2)\
             .reset_index()[ing_cols]
            
            return loaded_data


    def __str__(self):
        return self.csv_file.name
    
    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('bank-statement-content', args=[str(self.id)])

    
class gas_readings(models.Model):
    date = models.DateField()
    reading = models.IntegerField()
    submitted = models.BooleanField(default = False)
    annual_statement = models.BooleanField(default = False)
    
    class Meta:
        ordering = ['-date']

    def __str__(self):
        return self.date
        
class electricity_readings(models.Model):
    date = models.DateField()
    reading_1 = models.IntegerField()
    reading_2 = models.IntegerField()
    submitted = models.BooleanField(default = False)
    annual_statement = models.BooleanField(default = False)
    
    class Meta:
        ordering = ['-date']

    def __str__(self):
        return self.date
        
        

expenses/forms.py
from django import forms
from .models import expense_category
import datetime as dt


class upload_statement_form(forms.Form):
    file = forms.FileField(widget=forms.FileInput(attrs={'accept': ".csv"}))
    
class check_expense_form(forms.Form):
    categories = forms.ModelMultipleChoiceField(queryset = expense_category.objects.all(),
                                           widget = forms.CheckboxSelectMultiple(attrs={'class': "category-picker hide"
                                                        })
                                               )
    date_from = forms.DateField(label = 'Start date', 
                                widget = forms.DateInput(attrs={'class': "date-picker",
                                                                'type': 'date'
                                                        })
                               )
    date_to = forms.DateField(label = 'End date', 
                              widget = forms.DateInput(attrs={'class': "date-picker",
                                                                'type': 'date'
                                                        })
                             )
                             
class upload_reading_form(forms.Form):
     date = forms.DateField(label = "Date",
         widget = forms.DateInput(attrs={'class': "date-picker",
                                         'type': 'date'
                                 })
     )
     gas_reading = forms.IntegerField(label = "Gas")
     electricity_reading_1 = forms.IntegerField(label = "Eletricity 1")
     electricity_reading_2 = forms.IntegerField(label = "Eletricity 2")
     submitted = forms.BooleanField(label = "Submitted to supplier?")
     statement = forms.BooleanField(label = "Part of annual statement?")
     
         

expenses/views.py
from django.template import RequestContext
from django.shortcuts import render, redirect
from django.conf import settings
from django.http import JsonResponse
from django.core.paginator import Paginator
from django.http import Http404
from .forms import upload_statement_form, check_expense_form, upload_reading_form
from .models import expense_category, expense, ing_statement, ing_cols
from .utils import df_convert, iterate_categories, format_ctx, get_last_date
from django.core.files.base import ContentFile
from django.views.decorators.csrf import csrf_exempt
from django.views import generic
from io import StringIO
import pandas as pd
import datetime as dt
import re
import os
import json
from django.utils.timezone import datetime

#categories = {'value':[{'cat': cat.name} for cat in expense_category.objects.all()]}

def index(request):
     return render(request, 'index.html')

def process_record(row):
    try:
        expense_inst, created = expense.objects.get_or_create(date = row['date'], name = row['name'], 
                                                     amount = row['amount']
                                                    )
        if isinstance(expense_inst, expense):
            expense_inst = [expense_inst]
        for inst in expense_inst:
            if pd.notnull(row['category']):
                inst.category = expense_category.objects.get(name = row.category)
            if pd.isnull(row['description']):
                inst.description = None
            else:
                inst.description = row.description
            
            inst.save()
            
        return "success"
    except Exception as e:
        return str(e)

    
def retrieve_stats(cats, dfrom, dto):
    
    freq_cats = ['groceries', 'utilities', 'leisure']
    
    show_cats = ['total'] + cats + [c for c in freq_cats if c not in cats]

    
    expenses = expense.objects.filter(date__range=[dfrom, dto])
    period = (dto - dfrom).days 
    
    compare_from = (dfrom.replace(day = 1) - dt.timedelta(days=1)).replace(day = dfrom.day)
    compare_to = compare_from + dt.timedelta(period)
    
    compare_dates = [compare_from, compare_to]
    compare_expenses = expense.objects.filter(date__range = compare_dates)
    
    stats_dict = list(map(lambda cat: iterate_categories(cat, expenses, compare_expenses, cats),
                    show_cats[0:4]))

    stats_dict = format_ctx(stats_dict, compare_dates, period)
    return stats_dict

        
def expense_view(request):
    if request.method == 'GET':
        form = check_expense_form(request.GET)
        if form.is_valid():
            date_from = form.cleaned_data["date_from"]
            date_to = form.cleaned_data["date_to"]
            cat_objs = form.cleaned_data["categories"]
            categories = [c.name for c in cat_objs]
                
            try:  
                ## send to upload file
                if 'edit' in request.GET:

                    return redirect('expense-edit', cats = '-'.join([str(c.id) for c in cat_objs]), 
                                    dfrom = date_from, dto = date_to)
                
                ## show statistics
                if 'chart' in request.GET:
                    stats_dict = retrieve_stats(cats = categories, dfrom = date_from, dto = date_to)
 
                    form = check_expense_form(initial = {'date_from': date_from,
                                                         'date_to': date_to,
                                                         'categories': cat_objs
                                                        })

                    
                    return render(request, 'expenses/view_expense.html',
                                      {'form': form, 'stats': stats_dict}
                                     )

            except Exception as e:
                return JsonResponse({"fail": str(e)})

    date_to = datetime.today(); date_from = datetime.today()
    stats_dict = {}
    if expense.objects.exists():
        date_to = get_last_date()
        date_from = date_to.replace(day=1)
    if expense_category.objects.exists():
        stats_dict = retrieve_stats(cats=[cat.name for cat in expense_category.objects.all()],
                                    dfrom=date_from, dto=date_to)


    form = check_expense_form(initial={'categories': expense_category.objects.all(),
                                       'date_from': date_from,
                                       'date_to': date_to
                                       })
    
    return render(request, 'expenses/view_expense.html',
                  {'form': form, 'stats': stats_dict}
                 )


def expense_edit(request, cats, dfrom, dto):
    order_by = request.GET.get('order_by') or 'date'
    desc = request.GET.get('desc') == 'true'
    
    categories = expense_category.objects.filter(id__in = cats.split('-'))
    
    expenses = expense.objects.filter(date__range=[dfrom, dto]) 
    if len(categories)!=len(expense_category.objects.all()):
        expenses = expenses.filter(category__in = categories)

    if len(expenses) > 0:
        df = pd.DataFrame(list(expenses.values(
                            'date', 'name', 'amount', 'category__name', 'description'
                        ))).rename( columns={"category__name": "category"})
    else: 
        df = pd.DataFrame(columns = ing_cols)
    
    records = df_convert(df.sort_values([order_by], ascending = desc))
    paginator = Paginator(records, 7)
    pagenr = request.GET.get('page')
    page = paginator.get_page(pagenr)

    context = {'date_from': dfrom, 'date_to': dto, 'nrow': len(df),
               'page_obj': page, 'order_by': order_by, 'desc': desc, 
               'categories': json.dumps({'value':[{'cat': cat.name} for cat in expense_category.objects.all()]})
              }

    return render(request, 'expenses/ing_statement_detail.html', context)



@csrf_exempt
def ajax_view_expense(request):
    string_resp = request.POST.get('data','')
    #path = request.POST.get('fn','').replace('raw', 'cleansed')
    try:
        cleansed_data = pd.read_csv(StringIO(string_resp), sep = ';')
        resp = cleansed_data.astype({'name':'string', 'amount': 'float'})\
         .apply(lambda x: process_record(x), axis = 1)
        return JsonResponse({"abc": resp.to_json()})

        
#         cleansed_file = ing_statement.objects.get_or_create(csv_file = path, cleansed = True)
#         cleansed_file[0].csv_file.save(path.split('/')[-1], ContentFile(string_resp))
        #return JsonResponse({"success": 'yay'})
    except Exception as e:
        return JsonResponse({"fail": str(e)})


def upload_reading(request):
    form = upload_reading_form()
    return render(request, 'expenses/upload_reading.html', {'form': form})

@csrf_exempt    
def upload_bank_statement(request):

    if request.method == 'POST' and request.FILES:

        form = upload_statement_form(request.POST, request.FILES)
       
        if form.is_valid():
            statement_file = request.FILES['file']
            try:
                raw_file = ing_statement.objects.get(csv_file__endswith = statement_file.name, 
                                                     cleansed = False)
                raw_file.delete()
            except Exception as e:
                if 'it returned 2' in str(e):
                    ing_statement.objects.filter(csv_file__endswith = statement_file.name, 
                                                     cleansed = False).delete()
                else:
                    pass
                
            raw_file = ing_statement.objects.create(csv_file = statement_file, cleansed = False)
            return redirect(raw_file.get_absolute_url() + '#hash')


    form = upload_statement_form()
    try:
        max_date = get_last_date()
        ms = "The last recorded date is {}".format(max_date.strftime('%b %d'))
        if max_date < (dt.date.today() - dt.timedelta(days = 8)):
            ms += "<br> next <a href='https://mijn.ing.nl/login/' style='font-family: Muli;color:#572112;' target='_blank'>download</a> should be <b>{} &#8594; {}</b>".format(
                max_date + dt.timedelta(days=1), 
                dt.date.today() - dt.timedelta(days=1))
    except:
        ms = None
       
    return render(request, 'expenses/upload_bank_statement.html', {'form': form, 'ms': ms})



class ing_statement_detail_view(generic.DetailView):
    """Generic class-based detail view for an author."""
    model = ing_statement
    
    
    def get_context_data(self, **kwargs):
        order_by = self.request.GET.get('order_by') or 'date'
        desc = self.request.GET.get('desc') == 'true'
        
        # Call the base implementation first to get a context
        fn = self.object.csv_file.name
        #page = df_convert(self.object.load_raw().iloc[120:126])
        data = self.object.load_raw()\
            .sort_values([order_by], ascending = desc)
        records = df_convert(data)
        paginator = Paginator(records, 8)
        pagenr = self.request.GET.get('page')
        page = paginator.get_page(pagenr)
        
        nrow = len(data)
        record_count = len(expense.objects.all()) + nrow

        return {'date_from': self.object.date_from,
                'date_to': self.object.date_to,
                'nrow': len(data),
                'page_obj': page,
                'order_by': order_by,
                'desc': str(desc).lower(),
                'record_count': record_count,
                #'cleansed': fn,
                #'data': page.to_html(index=False, classes = "table-container"),
                #'data': create_html_table(page),
                #'data': process_dict(page),
                'categories': json.dumps({'value':[{'cat': cat.name} for cat in expense_category.objects.all()]})
               }

    
    
    
    

expenses/templates/expenses/ing_statement_detail.html
{% extends "base.html" %}
{% load statement_html %}
{% block content %}

<p> {%if date_from %}
    
   <button onclick="history.go(-1)">
       <i class="fa fa-chevron-circle-left" style="color:var(--yellow);padding-right:7px;"></i></button> 
    {{ nrow }} records from {{ date_from }} to {{ date_to }} 
    {% endif %}
    </p>

  {{ page_obj | dict_html | safe }} 
  
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a class="nav-page" href="#" data-id="?page=1">&laquo;</a>
            <a class="nav-page" href="#" data-id="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="page-current">
           {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
            <a class="nav-page" href="#" data-id="?page={{ page_obj.next_page_number }}">next</a>
            <a class="nav-page" href="#" id='check' data-id="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
        {% endif %}
        
        <button id="export" class="button" type="submit">save</button>
    </span>
    
</div>

{% if record_count %}
<p style="font-size:12px;color:#A2A39C">If the bank statement has not been processed before, there should be {{ record_count }} records in the database afterwards.</p>
{% endif %}

    
{% endblock %}

{% block custom_js %}
{% include 'expenses/table_js.html' %}

<script type="text/javascript">
    
    var url_params = new URLSearchParams(window.location.search);
    var order_by = url_params.get('order_by');
    if (order_by == null){ 
        order_by = "date"
    }
    
    $('#' + url_params.get('order_by')).css("color", "#b19693");
    
    $('.sort-table').on("click", function() {     
        new_order = $(this).parent().text(); 
        desc = url_params.get('desc') == "false";

        url = "?page=1&order_by=" + new_order + "&desc=" + desc.toString();
        window.location.href = url;
    });
    
    $('.nav-page').on("click", function() {
        var page_query = $(this).attr("data-id");
                 
        url = page_query + "&order_by=" + order_by + "&desc=" + url_params.get('desc');
        window.location.href = url;
         
        
    });
    
    
</script>

{% endblock custom_js %}

expenses/templates/expenses/table_js.html
<script type="text/javascript">
    function alert_saved() {
      $(".button").html('save');
 }
</script>

<script>

$(document).keydown(function(event){
    if ( (event.ctrlKey || event.metaKey) && event.keyCode === 83){
        event.stopPropagation();
        event.preventDefault();
        $("#export").click()
    }
    
    
    });
</script>    

<script type="text/javascript">
//        $(document).ready(function(){
//             $(document).on("click",".choice",function(){
//                 var value=$(this).text();
//                 var data_type=$(this).data("type");
//                 var input="<input type=text' class='input-data' value='"+value+"' class='form-control'>";
//                 $(this).html(input);
//                 $(this).removeClass("editable")
//             });
//     });
            $(".custom-select").each(function() {
  var classes = $(this).attr("class"),
      id      = $(this).attr("data-id"),
      val     = $(this).html();
  var template =  '<div class="' + classes + '">';
      template += '<span class="custom-select-trigger">' + val + '</span>';
      template += '<div class="custom-options">';     
      var categories = JSON.parse('{{ categories|safe }}');
      var options = categories["value"]
//       options = [{"cat":"groceries"},{"cat":"utilities"},{"cat":"leisure"},{"cat":"commute"},{"cat":"tools"},{"cat":"savings"},{"cat":"home"},{"cat":"renovation"},{"cat":"car"},{"cat":"travel"},{"cat":"hobbies"},{"cat":"presents"},{"cat":"clothings"},{"cat":"house"},{"cat":"misc"}]          

      $(options).each(function(index,value){ 
          template += '<span class="custom-option" data-value="' + value.cat + '">' + value.cat + '</span>';
      });  
  template += '</div></div>';
  
  $(this).wrap('<div class="custom-select-wrapper"></div>');
  $(this).hide();
  $(this).after(template);
});


$(".custom-option:first-of-type").hover(function() {
  $(this).parents(".custom-options").addClass("option-hover");
}, function() {
  $(this).parents(".custom-options").removeClass("option-hover");
});

$(".custom-select-trigger").on("click", function() {
  $('html').one('click',function() {
    $(".custom-select").removeClass("opened");
  });
  $(this).parents(".custom-select").toggleClass("opened");
  event.stopPropagation();
});

$(".custom-option").on("click", function() {
  alert_saved();
  $(this).parents(".custom-select-wrapper").children('td').html($(this).data("value"));
  $(this).parents(".custom-options").find(".custom-option").removeClass("selection");
  $(this).addClass("selection");
  $(this).parents(".custom-select").removeClass("opened");
  $(this).parents(".custom-select").find(".custom-select-trigger").text($(this).text());
});
    
    </script>



<script type="text/javascript">
    $('#export').click(function() {
  var titles = [];
  var data = [];

  /*
   * Get the table headers, this will be CSV headers
   * The count of headers will be CSV string separator
   */
  $('.table-container th').each(function() {
    titles.push($(this).text());
  });

  /*
   * Get the actual data, this will contain all the data, in 1 array
   */
  $('.table-container td').each(function() {
    var shadow = $(this).find('input').val()
    if (!!shadow) { 
        data.push(shadow);
    }else{
        data.push($(this).text());
    }
      
  });
        
  
  /*
   * Convert our data to CSV string
   */
  var CSVString = prepCSVRow(titles, titles.length, '');
  CSVString = prepCSVRow(data, titles.length, CSVString);
        

  /*
   * Make CSV downloadable
   */
//   var downloadLink = document.createElement("a");
//   var blob = new Blob(["\ufeff", CSVString]);
//   var url = URL.createObjectURL(blob);
//   downloadLink.href = url;
//   downloadLink.download = "data.csv";

//   /*
//    * Actually download CSV
//    */
//   document.body.appendChild(downloadLink);
//   downloadLink.click();
//   document.body.removeChild(downloadLink);
        

    $.ajax({
                url:"{% url 'ajax-view-expense' %}",
                type:"POST",
                data: {'data': CSVString,
                       //'fn': "{{cleansed|safe}}"
                      },
            }).done(function(response){
                console.log(response);
                $(".button").html('success')
            }).fail(function(){
               console.log("Error Occured");
            });
        
});

   /*
* Convert data array to CSV string
* @param arr {Array} - the actual data
* @param columnCount {Number} - the amount to split the data into columns
* @param initial {String} - initial string to append to CSV string
* return {String} - ready CSV string
*/
function prepCSVRow(arr, columnCount, initial) {
  var row = ''; // this will hold data
  var delimeter = ';'; // data slice separator, in excel it's `;`, in usual CSv it's `,`
  var newLine = '\r\n'; // newline separator for CSV row

  /*
   * Convert [1,2,3,4] into [[1,2], [3,4]] while count is 2
   * @param _arr {Array} - the actual array to split
   * @param _count {Number} - the amount to split
   * return {Array} - splitted array
   */
  function splitArray(_arr, _count) {
    var splitted = [];
    var result = [];
    _arr.forEach(function(item, idx) {
      if ((idx + 1) % _count === 0) {
        splitted.push(item);
        result.push(splitted);
        splitted = [];
      } else {
        splitted.push(item);
      }
    });
    return result;
  }
  var plainArr = splitArray(arr, columnCount);
  // don't know how to explain this
  // you just have to like follow the code
  // and you understand, it's pretty simple
  // it converts `['a', 'b', 'c']` to `a,b,c` string
  plainArr.forEach(function(arrItem) {
    arrItem.forEach(function(item, idx) {
      row += item + ((idx + 1) === arrItem.length ? '' : delimeter);
    });
    row += newLine;
  });
  return initial + row;
}
    
    </script>

expenses/templates/expenses/upload_bank_statement.html
{% extends "base.html" %}
{% block content %}

<p>The league for fighting charted accountancy</p>
<form action="{% url 'bank-statement-upload' %}" method="post" class="uploader" enctype="multipart/form-data" data-ajax="false">
    {% csrf_token %}
    {% for field in form %}
        {% for error in field.errors %}
                    <div class="alert alert-error" style = "color:#4939F3">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}   
    
     <label for="id_file" id="file-drag">
            {{ field }}
         <div id="start">
      <i class="fa fa-download" aria-hidden="true"></i>
      <div style="line-height:24px;font-size:14px">
          {% if ms %}
           {{ ms|safe }}
          {% else %}
          Select file
          {% endif %}
          
             </div>
    </div>
    <div id="response" class="hidden">
      <div id="messages"></div>
    </div>
         <input type="submit" id="file-upload-btn" class="btn btn-primary"value= 'Load records'>
  </label>
    {% endfor %}
</form>
    
{% endblock %}

expenses/templates/expenses/upload_reading.html
{% extends "base.html" %}
{% block content %}

<p>Energy</p>
{{ form }}

{% endblock %}

expenses/templates/expenses/view_expense.html
{% extends "base.html" %}
{% block content %}

<form action="{% url 'expense-content' %}" method="get" class='expense-form'>
    {% csrf_token %}
    <p class="division"> Records in <a href="#" class="category-select"> all </a> categories
        {% for field in form %} 
            {% if field.name == 'date_from' %}
               from {{ field }}
            {% elif field.name == 'date_to' %}
               to {{ field }}
            {% endif %}
        {% endfor %}
        of money leaving our pocket..
        <button name="chart" id="chart" type="submit" style='display:none'></button>
        <button href = "#" name="edit" type="submit"><i class="fa fa-database" aria-hidden="true"></i></button>
        <a href = "{% url 'bank-statement-upload' %}"><i class="fa fa-plus-square" aria-hidden="true"></i></a>
        </p>
    <!-- CONTENT -->
          <div style="display: flex">
              
        {% for field in form %} 
            {% if field.name == 'categories' %}
    <div class="category-wrapper"> {{ field }} </div>
            {% endif %}
        {% endfor %}
        
       <div id="shrinkage"  style="display: flex;padding-right:70px;width:80%">
        <!-- info -->
        <div id="container5">
          
          {% for stat in stats %}  
          <div id="score{{ stat.indx }}" class="scoreContainer">
              <div class="score-title">{{ stat.cat|safe }}</div>
              <div class="score">&euro;{{ stat.sum }}</div>
              <div class="scoreInc">{{ stat.diff|safe }}</div>
              {% if stat.txt %}
              <div class="scoreInc text">{{ stat.txt|safe }}</div>
              {% endif %}
        </div>
            {% endfor %}
            
          
            </div>
        
        
        <!-- chart -->
         <div id="container4" style="background-color:#e9dfd5;" data-highcharts-chart="0"><div id="highcharts-hqqrsdo-0" dir="ltr" class="highcharts-container"></div></div>
            
            </div>
        
      </div>
    
    
</form>


    
{% endblock %}

{% block custom_js %}
<script>
$(document).ready(function(){
  $(".category-select").click(function(e){
      e.stopPropagation();
    $(".category-picker").toggleClass("hide");
  });
    $('input.category-picker').wrap( '<i class="fa fa-check"></i>' )
    $(document).click(function(){  
  $(".category-picker").addClass("hide");
  });
  $(".category-picker").click(function(e){  
      e.stopPropagation();
  })
    
    
  $("input.category-picker").each(function() {
    var opacity = "0";
      if ($(this).is(":checked")){ opacity = "1"};
      $(this).parent().css("opacity", opacity);
  });
  if ($('input.category-picker').not(':checked').length != 0){
          $(".category-select").html('selected')
      }else{
          $(".category-select").html('all')
      }
    
  $("input.category-picker").click(function(e){  
      var opacity = "0";
      if ($(this).is(":checked")){ opacity = "1"};
      $(this).parent().css("opacity", opacity);
      
      if ($('input.category-picker').not(':checked').length != 0){
          $(".category-select").html('selected')
      }else{
          $(".category-select").html('all')
      }
  })
    
    $(".chart").click()
  
});
</script>

<script>

$(document).keydown(function(event){
    if (event.keyCode === 13) {
        event.stopPropagation();
        event.preventDefault();
        $("#chart").click();
    }
    
    if ( event.shiftKey && event.keyCode === 67){
        $(".category-select").click()
    }
    
    
    });
</script>    

<script>
$(document).ready(function(){
  $("#id_categories").append('<li><a href="#" class="select-all">Click all</a></li>');
  $('.select-all').click(function(){
    $(".category-picker").click();
});
});
</script>

{% include 'expenses/table_js.html' %}

{% endblock custom_js %}